// Generated by CoffeeScript 1.4.0
(function() {

  $('document').ready(function() {
    var animateIndependent, animateStaySmall, animateStickers, animateTopTalent, animationDelay, animationTime, resetStickers;
    animationTime = 1000;
    animationDelay = 500;
    resetStickers = function() {
      $('#stay_small_sticker').animate({
        opacity: 0
      }, function() {
        return $('#stay_small_sticker').css('position', 'relative').css('left', '-100px').css('top', '100px');
      });
      $('#independent_sticker').animate({
        opacity: 0
      }, function() {
        return $('#independent_sticker').css('position', 'relative').css('top', '150px');
      });
      return $('#top_talent_sticker').animate({
        opacity: 0
      }, function() {
        return $('#top_talent_sticker').css('position', 'relative').css('right', '-100px').css('top', '100px');
      });
    };
    animateStaySmall = function() {
      return $('#stay_small_sticker').animate({
        top: ['-=100', 'swing'],
        left: ['+=100', 'swing'],
        opacity: 1
      }, animationTime);
    };
    animateIndependent = function() {
      return $('#independent_sticker').animate({
        top: ['-=150', 'swing'],
        opacity: 1
      }, animationTime);
    };
    animateTopTalent = function() {
      return $('#top_talent_sticker').animate({
        top: ['-=100', 'swing'],
        right: ['+=100', 'swing'],
        opacity: 1
      }, animationTime);
    };
    animateStickers = function() {
      resetStickers();
      animateStaySmall();
      setTimeout(function() {
        return animateIndependent();
      }, animationDelay);
      return setTimeout(function() {
        return animateTopTalent();
      }, animationDelay * 2);
    };
    if (document.documentElement.clientWidth > 600) {
      resetStickers();
      return $('#about').waypoint(function(direction) {
        if (direction === 'down') {
          return animateStickers();
        }
      }, {
        offset: 500
      });
    }
  });

}).call(this);
