// Generated by CoffeeScript 1.4.0
(function() {

  $('document').ready(function() {
    var animateViking, backgrounId, isVikingAnimated;
    backgrounId = Math.floor((Math.random() * 4) + 1);
    $('#company').css('background-image', 'url(img/main/bg-photo' + backgrounId + '.jpg)');
    $('#company').parallax("50%", 0.7, false);
    animateViking = function() {
      return $('#viking').animate({
        top: ['-=215', 'swing']
      }, 1000, function() {
        return $('#viking').css('z-index', '2');
      });
    };
    if (document.documentElement.clientWidth > 600) {
      return setTimeout(function() {
        return animateViking();
      }, 700);
    } else {
      isVikingAnimated = false;
      return $('#about').waypoint(function() {
        if (!isVikingAnimated) {
          isVikingAnimated = true;
          return animateViking();
        }
      }, {
        offset: 500
      });
    }
  });

}).call(this);
