// Generated by CoffeeScript 1.4.0
(function() {

  $('document').ready(function() {
    var init, pendulumswing, rotation, swingtime;
    rotation = 5;
    swingtime = 1000;
    init = function() {
      return $('#get_in_touch_pivot').stop().animate({
        rotate: rotation
      }, 0, function() {
        $('#get_in_touch_pivot').css("display", "block");
        return pendulumswing();
      });
    };
    pendulumswing = function() {
      return $('#get_in_touch_pivot').animate({
        rotate: rotation
      }, swingtime, "swing", function() {
        if (rotation === 0) {
          return;
        }
        if (rotation > 0) {
          rotation -= 0.5;
        } else {
          rotation += 0.5;
        }
        rotation *= -1;
        return pendulumswing();
      });
    };
    return $('#contact').waypoint(function(direction) {
      if (direction === 'down') {
        rotation = 5;
        swingtime = 1000;
        return init();
      }
    }, {
      offset: 500
    });
  });

}).call(this);
