// Generated by CoffeeScript 1.4.0
(function() {

  $('document').ready(function() {
    var slideId;
    $('#games').parallax("50%", 0.2, false);
    slideId = 1;
    return setInterval(function() {
      return $('#slideshow').fadeOut(function() {
        slideId += 1;
        if (slideId > 3) {
          slideId = 1;
        }
        $('#slideshow').css('background-image', 'url(img/main/slide' + slideId + '.png)');
        return $('#slideshow').fadeIn();
      });
    }, 5000);
  });

}).call(this);
